project : NGN_journal_2

experiments:
-   dataset: ['cifar10']
    arch: ["res18"]
    seed: [0,1,2]
    opt:
      alg: ['sgdm']
      ep: [30]
      lr: [0.003, 0.001]
      bs: [128]
      wd: [0.0, 0.0005]
      beta1: [0.9]
      lr_decay : [False]