project : NGN_journal_3

experiments:
-   dataset: ['cifar10']
    arch: ["res18"]
    seed: [0,1,2]
    opt:
      alg: ['ngn']
      ep: [30]
      lr: [3, 1, 0.3, 0.1]
      bs: [128]
      wd: [0.0]
      beta1: [0]
      lr_decay : [False]